### PR TITLE
QuickCreate support

### PR DESCRIPTION
**Pull request by thathi**
#120

### CODE REVIEW

**Comment by mVermaat** [comment]
Looks good. How are you planning on using it in your scenarios?

**Comment by thathi** [comment]
In my case I have add new buttons in grids and by clicking on it it will open a quick create form so using as follows. 
image

And my command looks like as follows (bit ugly yet to make it simple and refactor). 

image

**Comment by mVermaat** [comment]
Merged into feature branch. I'll run a couple of tests and play around with it before merging into master.

**Pull request merged**
